"""
PLUTO 1D Spherical Solar Wind Wrapper
Wrapper for HUXt integration
"""
import os
import shutil
import subprocess
import numpy as np
import tempfile
from pathlib import Path

# Physical constants
PROTON_MASS = 1.67262192e-24  # g
BOLTZMANN = 1.380649e-16      # erg/K
AU = 1.496e13                  # cm


class PLUTOCustomBCWrapper:
    """
    Wrapper for PLUTO 1D spherical hydrodynamics solver.
    Handles time-dependent boundary conditions.
    
    Since PLUTO is a batch C code, this wrapper:
    1. Creates a temporary working directory
    2. Generates init.c with time-dependent boundary conditions
    3. Compiles and runs PLUTO
    4. Reads outputs with pyPLUTO
    """
    
    def __init__(self, pluto_dir, gamma=5.0/3.0, r_inner=1.496e12, r_outer=1.646e13,
                 nr=200, cfl=0.4, t_offset=0.0, work_dir=None):
        """
        Initialize PLUTO wrapper.
        
        Parameters
        ----------
        pluto_dir : str
            Path to PLUTO installation directory
        gamma : float
            Adiabatic index (default 5/3)
        r_inner, r_outer : float
            Inner and outer radial boundaries in cm
        nr : int
            Number of radial grid points
        cfl : float
            CFL number for time-stepping
        t_offset : float
            Time offset in seconds (for model time vs simulation time)
        work_dir : str, optional
            Working directory for PLUTO runs. If None, creates temp directory.
        """
        self.pluto_dir = Path(pluto_dir).resolve()
        self.gamma = gamma
        self.r_inner = r_inner
        self.r_outer = r_outer
        self.nr = nr
        self.cfl = cfl
        self.t_offset = t_offset
        
        # Verify PLUTO installation
        if not self.pluto_dir.exists():
            raise FileNotFoundError(f"PLUTO directory not found: {self.pluto_dir}")
        
        pluto_src = self.pluto_dir / "Src"
        if not pluto_src.exists():
            raise FileNotFoundError(f"PLUTO Src directory not found: {pluto_src}")
        
        # Create working directory
        if work_dir is None:
            self.work_dir = Path(tempfile.mkdtemp(prefix="pluto_run_"))
            self._temp_dir = True
        else:
            self.work_dir = Path(work_dir).resolve()
            self.work_dir.mkdir(parents=True, exist_ok=True)
            self._temp_dir = False
        
        # Initialize state
        self._current_time = 0.0  # Simulation time (starts at 0)
        self._current_step = 0
        self._bc_func = None
        self._last_output_num = -1
        
        # Setup problem files
        self._setup_pluto_problem()
        
        print(f"PLUTO wrapper initialized:")
        print(f"  Working directory: {self.work_dir}")
        print(f"  Domain: {r_inner/AU:.3f} - {r_outer/AU:.3f} AU ({nr} cells)")
        print(f"  γ = {gamma:.4f}, CFL = {cfl}")
    
    def _setup_pluto_problem(self):
        """
        Create PLUTO problem files (definitions.h, pluto.ini, init.c, makefile).
        """
        # Create definitions.h
        definitions_content = f"""/* ///////////////////////////////////////////////////////////////////// */
/*! 
  \\file definitions.h
  \\brief 1D Spherical Solar Wind Problem (generated by PLUTOCustomBCWrapper)
*/
/* ///////////////////////////////////////////////////////////////////// */

#define  PHYSICS                        HD
#define  DIMENSIONS                     1
#define  GEOMETRY                       SPHERICAL
#define  BODY_FORCE                     NO
#define  COOLING                        NO
#define  RECONSTRUCTION                 WENO3
#define  TIME_STEPPING                  RK3
#define  NTRACER                        0
#define  PARTICLES                      NO
#define  USER_DEF_PARAMETERS            3

/* -- physics dependent declarations -- */

#define  DUST_FLUID                     NO
#define  EOS                            IDEAL
#define  ENTROPY_SWITCH                 NO
#define  THERMAL_CONDUCTION             NO
#define  VISCOSITY                      NO
#define  ROTATING_FRAME                 NO

/* -- user-defined parameters (labels) -- */

#define  N_PROTONS                      0
#define  V_WIND                         1
#define  T_WIND                         2

/* [Beg] user-defined constants (do not change this line) */

/* [End] user-defined constants (do not change this line) */
"""
        
        # Create pluto.ini
        pluto_ini_content = f"""[Grid]

X1-grid    1    {self.r_inner:.6e}    {self.nr}    u    {self.r_outer:.6e}
X2-grid    1    0.0    1    u    1.0
X3-grid    1    0.0    1    u    1.0

[Chombo Refinement]

Levels              4
Ref_ratio           2 2 2 2 2
Regrid_interval     2 2 2 2
Refine_thresh       0.3
Tag_buffer_size     3
Block_factor        4
Max_grid_size       32
Fill_ratio          0.75

[Time]

CFL              {self.cfl}
CFL_max_var      1.1
tstop            1.0
first_dt         1.e-9

[Solver]

Solver         hll

[Boundary]

X1-beg        userdef
X1-end        outflow
X2-beg        outflow
X2-end        outflow
X3-beg        outflow
X3-end        outflow

[Static Grid Output]

uservar    0
dbl        -1.0  -1  single_file
flt       -1.0  -1  single_file
vtk       -1.0  -1  single_file
tab       -1.0  -1
ppm       -1.0  -1
png       -1.0  -1
log        100
analysis  -1.0  -1

[Chombo HDF5 output]

Checkpoint_interval  -1.0  0
Plot_interval         1.0  0

[Parameters]

N_PROTONS            200.0
V_WIND               4.0e7
T_WIND               1.0e6
"""
        
        # Write files
        (self.work_dir / "definitions.h").write_text(definitions_content)
        (self.work_dir / "pluto.ini").write_text(pluto_ini_content)
        
        # Create initial init.c (will be updated with BC function later)
        self._write_init_c(None)
        
        # Determine architecture for PLUTO config
        import platform
        system = platform.system()
        if system == "Darwin":
            arch = "Linux.gcc.defs"  # On macOS, use Linux config (works with gcc)
        else:
            arch = "Linux.gcc.defs"
        
        # Create minimal makefile that includes PLUTO's standard makefile
        # We'll copy the makefile from pluto_1d_wind as it's known to work
        pluto_1d_wind_makefile = Path("/Users/vy902033/Library/CloudStorage/Dropbox/python_repos/HUXt5/pluto_1d_wind/makefile")
        
        if pluto_1d_wind_makefile.exists():
            # Copy working makefile and update PLUTO_DIR
            makefile_content = pluto_1d_wind_makefile.read_text()
            makefile_content = makefile_content.replace(
                "PLUTO_DIR    = /Users/vy902033/Library/CloudStorage/Dropbox/python_repos/HUXt5/PLUTO",
                f"PLUTO_DIR    = {self.pluto_dir}"
            )
            (self.work_dir / "makefile").write_text(makefile_content)
        else:
            # Fallback to simple makefile
            makefile_content = f"""ARCH         = {arch}
PLUTO_DIR    = {self.pluto_dir}
SRC          = $(PLUTO_DIR)/Src

include $(PLUTO_DIR)/Config/$(ARCH)
"""
            (self.work_dir / "makefile").write_text(makefile_content)
        
        (self.work_dir / "sysconf.out").write_text(f"# Generated by PLUTOCustomBCWrapper\n")
    
    def _write_init_c(self, bc_func_at_time=None):
        """
        Generate init.c with Parker solution initialization and boundary conditions.
        
        Parameters
        ----------
        bc_func_at_time : tuple (rho_bc, v_bc, T_bc) or None
            Boundary condition values. If None, uses default Parker solution.
        """
        if bc_func_at_time is None:
            # Default initial conditions (will be updated later)
            n_bc = 200.0  # protons/cm³
            v_bc = 4.0e7  # cm/s
            T_bc = 1.0e6  # K
            rho_bc = n_bc * PROTON_MASS
        else:
            rho_bc, v_bc, T_bc = bc_func_at_time
        
        n_bc = rho_bc / PROTON_MASS
        
        # Compute Parker solution profile for initialization
        r_grid = np.linspace(self.r_inner, self.r_outer, self.nr)
        v_parker, n_parker, T_parker, rho_parker = _compute_parker_nozzle_solution(
            r_grid, v_bc, n_bc, T_bc, self.gamma
        )
        
        # Generate Parker profile lookup table for init.c
        parker_table = "  /* Parker solution lookup table (precomputed) */\n"
        parker_table += f"  static double r_table[{len(r_grid)}] = {{\n    "
        parker_table += ", ".join([f"{r_val:.6e}" for r_val in r_grid])
        parker_table += "\n  };\n"
        
        parker_table += f"  static double v_table[{len(r_grid)}] = {{\n    "
        parker_table += ", ".join([f"{v_val:.6e}" for v_val in v_parker])
        parker_table += "\n  };\n"
        
        parker_table += f"  static double n_table[{len(r_grid)}] = {{\n    "
        parker_table += ", ".join([f"{n_val:.6e}" for n_val in n_parker])
        parker_table += "\n  };\n"
        
        parker_table += f"  static double T_table[{len(r_grid)}] = {{\n    "
        parker_table += ", ".join([f"{T_val:.6e}" for T_val in T_parker])
        parker_table += "\n  };\n"
        
        init_c_content = f"""/* ///////////////////////////////////////////////////////////////////// */
/*!
  \\file  init.c
  \\brief 1D Spherical Solar Wind Initialization
         Generated by PLUTOCustomBCWrapper with Parker nozzle solution
*/
/* ///////////////////////////////////////////////////////////////////// */

#include "pluto.h"

/* Physical constants */
#define BOLTZMANN  1.380649e-16  /* erg/K */
#define PROTON_MASS 1.67262192e-24  /* g */
#define N_PARKER_TABLE {len(r_grid)}

/* Linear interpolation helper */
static double interp1d(double x, double *x_table, double *y_table, int n) {{
  int i;
  double frac;
  
  /* Handle boundaries */
  if (x <= x_table[0]) return y_table[0];
  if (x >= x_table[n-1]) return y_table[n-1];
  
  /* Find bracketing indices */
  for (i = 0; i < n-1; i++) {{
    if (x >= x_table[i] && x < x_table[i+1]) {{
      frac = (x - x_table[i]) / (x_table[i+1] - x_table[i]);
      return y_table[i] + frac * (y_table[i+1] - y_table[i]);
    }}
  }}
  return y_table[n-1];
}}

/* ********************************************************************* */
void Init (double *v, double x1, double x2, double x3)
/*!
 * Initialize domain with Parker nozzle solution (isentropic quasi-1D flow)
 *********************************************************************** */
{{
  double r, n, v_radial, T, rho, P;
  
  g_gamma = {self.gamma};
  
{parker_table}
  
  /* Current position */
  r = x1;
  
  /* Interpolate Parker solution from precomputed table */
  v_radial = interp1d(r, r_table, v_table, N_PARKER_TABLE);
  n = interp1d(r, r_table, n_table, N_PARKER_TABLE);
  T = interp1d(r, r_table, T_table, N_PARKER_TABLE);
  
  rho = n * PROTON_MASS;
  P = n * BOLTZMANN * T;
  
  /* Set primitive variables */
  v[RHO] = rho;
  v[VX1] = v_radial;
  v[VX2] = 0.0;
  v[VX3] = 0.0;
  v[PRS] = P;
}}

/* ********************************************************************* */
void InitDomain (Data *d, Grid *grid)
/*!
 * Assign initial condition by looping over the computational domain.
 *********************************************************************** */
{{
  /* Nothing extra needed here */
}}

/* ********************************************************************* */
void Analysis (const Data *d, Grid *grid)
/*!
 * Perform analysis during simulation
 *********************************************************************** */
{{
  /* Not used */
}}

/* ********************************************************************* */
void UserDefBoundary (const Data *d, RBox *box, int side, Grid *grid) 
/*! 
 * Apply time-dependent boundary conditions at inner boundary.
 * Values are set from g_inputParam which can be updated between runs.
 *********************************************************************** */
{{
  int i, j, k;
  double *x1 = grid->x[IDIR];
  double *x2 = grid->x[JDIR];
  double *x3 = grid->x[KDIR];
  double ***rho = d->Vc[RHO];
  double ***vx1 = d->Vc[VX1];
  double ***vx2 = d->Vc[VX2];
  double ***vx3 = d->Vc[VX3];
  double ***prs = d->Vc[PRS];
  
  double n_bc, v_bc, T_bc, rho_bc, P_bc;
  
  /* Get current BC values from parameters */
  n_bc = g_inputParam[N_PROTONS];
  v_bc = g_inputParam[V_WIND];
  T_bc = g_inputParam[T_WIND];
  rho_bc = n_bc * PROTON_MASS;
  P_bc = n_bc * BOLTZMANN * T_bc;
  
  if (side == X1_BEG) {{
    BOX_LOOP(box, k, j, i) {{
      rho[k][j][i] = rho_bc;
      vx1[k][j][i] = v_bc;
      vx2[k][j][i] = 0.0;
      vx3[k][j][i] = 0.0;
      prs[k][j][i] = P_bc;
    }}
  }}
}}
"""
        (self.work_dir / "init.c").write_text(init_c_content)
    
    def set_custom_bc(self, bc_func):
        """
        Set custom boundary condition function.
        
        Parameters
        ----------
        bc_func : callable
            Function with signature bc_func(r, t) -> (rho, v, T)
            where r is radial position array (cm), t is time (s)
            Returns: rho (g/cm³), v (cm/s), T (K) as arrays
        """
        self._bc_func = bc_func
    
    def set_time_varying_bc(self, time_array, rho_array, v_array, T_array):
        """
        Set time-varying boundary conditions using lookup tables.
        CRITICAL: Embeds BC tables directly in init.c (not separate file).
        This is the only approach that works for PLUTO HD simulations.
        
        Parameters
        ----------
        time_array : ndarray
            Time values (seconds)
        rho_array : ndarray
            Density values at inner boundary (g/cm³)
        v_array : ndarray
            Velocity values at inner boundary (cm/s)
        T_array : ndarray
            Temperature values at inner boundary (K)
        """
        # Store BC data for init.c generation
        self._bc_time_array = time_array
        self._bc_rho_array = rho_array
        self._bc_v_array = v_array
        self._bc_T_array = T_array
        
        # Regenerate init.c with BC tables embedded
        self._write_init_c_with_time_bc(time_array, rho_array, v_array, T_array)
        
        n_times = len(time_array)
        print(f"  Generated init.c with {n_times} BC time points embedded")
        print(f"    Time range: {time_array[0]:.2e} to {time_array[-1]:.2e} s")
        print(f"    T_OFFSET: {self.t_offset:.2e} s")
        print(f"    V range: {v_array.min():.2e} to {v_array.max():.2e} cm/s")
        print(f"    V variation: {(v_array.max() - v_array.min())/v_array.mean() * 100:.1f}%")
    
    def _write_init_c_with_time_bc(self, time_array, rho_array, v_array, T_array):
        """
        Generate init.c with time-varying BC lookup tables embedded.
        This is the WORKING approach - UserDefBoundary in init.c gets called.
        Separate userdef_boundary.c does NOT work for HD simulations.
        """
        n_times = len(time_array)
        
        # Format BC lookup tables for C arrays (5 values per line)
        def format_array(arr, name):
            lines = []
            lines.append(f"static double {name}[{len(arr)}] = {{")
            for i in range(0, len(arr), 5):
                chunk = arr[i:i+5]
                line = "  " + ", ".join([f"{val:.6e}" for val in chunk])
                if i + 5 < len(arr):
                    line += ","
                lines.append(line)
            lines.append("};")
            return "\n".join(lines)
        
        t_table = format_array(time_array, "t_bc_table")
        rho_table = format_array(rho_array, "rho_bc_table")
        v_table = format_array(v_array, "v_bc_table")
        T_table = format_array(T_array, "T_bc_table")
        
        # Generate init.c with embedded BC tables
        init_c_content = f"""/* ///////////////////////////////////////////////////////////////////// */
/*!
  \\file  init.c
  \\brief 1D Spherical Solar Wind with Time-Varying Boundary Conditions
         Generated by PLUTOCustomBCWrapper for HUXt integration
         
  CRITICAL: BC lookup tables are embedded HERE (not in separate file).
  This is the ONLY approach that works for PLUTO HD simulations.
  UserDefBoundary() in init.c gets called; external files do NOT.
*/
/* ///////////////////////////////////////////////////////////////////// */

#include "pluto.h"

/* Physical constants */
#define BOLTZMANN  1.380649e-16  /* erg/K */
#define PROTON_MASS 1.67262192e-24  /* g */

/* Time offset: converts g_time (starts at 0) to model_time coordinate */
#define T_OFFSET {self.t_offset:.6e}

/* Boundary condition lookup tables */
#define N_BC_TIMES {n_times}

{t_table}

{rho_table}

{v_table}

{T_table}

/* ********************************************************************* */
/* Linear interpolation with binary search */
static double interp1d(double t, double *t_table, double *y_table, int n) {{
  int left, right, mid;
  double frac;
  
  /* Handle boundaries */
  if (t <= t_table[0]) return y_table[0];
  if (t >= t_table[n-1]) return y_table[n-1];
  
  /* Binary search for bracketing interval */
  left = 0;
  right = n - 1;
  while (right - left > 1) {{
    mid = (left + right) / 2;
    if (t < t_table[mid])
      right = mid;
    else
      left = mid;
  }}
  
  /* Linear interpolation */
  frac = (t - t_table[left]) / (t_table[right] - t_table[left]);
  return y_table[left] + frac * (y_table[right] - y_table[left]);
}}

/* ********************************************************************* */
void Init (double *v, double x1, double x2, double x3)
/*!
 * Initialize domain with initial BC values (t=0).
 * Domain will evolve via UserDefBoundary() applying time-varying BCs.
 *********************************************************************** */
{{
  double r, rho_init, v_init, T_init, prs_init;
  
  g_gamma = {self.gamma};
  
  /* Get initial BC values at t=0 (first entry in tables) */
  rho_init = rho_bc_table[0];
  v_init = v_bc_table[0];
  T_init = T_bc_table[0];
  prs_init = rho_init * BOLTZMANN * T_init / PROTON_MASS;
  
  /* Simple initial profile - will be replaced by time evolution */
  r = x1;
  
  /* Set primitive variables */
  v[RHO] = rho_init * (x1 / {self.r_inner:.6e});  /* Roughly Parker-like */
  v[VX1] = v_init;
  v[VX2] = 0.0;
  v[VX3] = 0.0;
  v[PRS] = prs_init;
}}

/* ********************************************************************* */
void InitDomain (Data *d, Grid *grid)
/*!
 * Assign initial condition by looping over the computational domain.
 *********************************************************************** */
{{
  /* Nothing extra needed */
}}

/* ********************************************************************* */
void Analysis (const Data *d, Grid *grid)
/*!
 * Perform runtime analysis (called each timestep).
 *********************************************************************** */
{{
  /* Not used */
}}

/* ********************************************************************* */
void UserDefBoundary (const Data *d, RBox *box, int side, Grid *grid) 
/*!
 * Apply TIME-VARYING boundary conditions at inner radius.
 * This function IS called by PLUTO when it's in init.c.
 * 
 * Key insight from sunRunner1D: UserDefBoundary must be in init.c,
 * not in a separate file, for HD simulations to work correctly.
 *********************************************************************** */
{{
  int   i, j, k;
  double *x1, *x2, *x3;
  double rho_bc, v_bc, T_bc, prs_bc, n_bc;
  double t_current;

  x1 = grid->x[IDIR];
  x2 = grid->x[JDIR];
  x3 = grid->x[KDIR];

  /* Convert g_time (starts at 0) to model_time coordinate */
  t_current = g_time + T_OFFSET;

  /* Interpolate boundary conditions at current time from lookup tables */
  rho_bc = interp1d(t_current, t_bc_table, rho_bc_table, N_BC_TIMES);
  v_bc = interp1d(t_current, t_bc_table, v_bc_table, N_BC_TIMES);
  T_bc = interp1d(t_current, t_bc_table, T_bc_table, N_BC_TIMES);
  
  /* Compute pressure from ideal gas law */
  n_bc = rho_bc / PROTON_MASS;
  prs_bc = n_bc * BOLTZMANN * T_bc;

  /* Apply inner boundary conditions */
  if (side == X1_BEG) {{
    BOX_LOOP(box, k, j, i) {{
      d->Vc[RHO][k][j][i] = rho_bc;
      d->Vc[VX1][k][j][i] = v_bc;
      d->Vc[VX2][k][j][i] = 0.0;
      d->Vc[VX3][k][j][i] = 0.0;
      d->Vc[PRS][k][j][i] = prs_bc;
    }}
  }}
}}
"""
        
        (self.work_dir / "init.c").write_text(init_c_content)
    
    def apply_custom_bc(self):
        """
        Apply custom boundary conditions by updating pluto.ini parameters.
        This will be used at the start of the next PLUTO run.
        """
        if self._bc_func is None:
            return
        
        # Evaluate BC at inner boundary at current time
        model_time = self._current_time + self.t_offset
        r_bc = np.array([self.r_inner])
        
        rho_bc, v_bc, T_bc = self._bc_func(r_bc, model_time)
        
        # Extract scalar values
        if hasattr(rho_bc, '__len__'):
            rho_bc = rho_bc[0]
        if hasattr(v_bc, '__len__'):
            v_bc = v_bc[0]
        if hasattr(T_bc, '__len__'):
            T_bc = T_bc[0]
        
        n_bc = rho_bc / PROTON_MASS
        
        # Update init.c with new BC
        self._write_init_c((rho_bc, v_bc, T_bc))
        
        # Update pluto.ini parameters
        self._update_pluto_ini_params(n_bc, v_bc, T_bc)
    
    def _update_pluto_ini_params(self, n_bc, v_bc, T_bc):
        """Update parameters in pluto.ini"""
        ini_path = self.work_dir / "pluto.ini"
        content = ini_path.read_text()
        
        # Replace parameter values
        import re
        content = re.sub(r'N_PROTONS\s+[\d.e+-]+', f'N_PROTONS            {n_bc:.6e}', content)
        content = re.sub(r'V_WIND\s+[\d.e+-]+', f'V_WIND               {v_bc:.6e}', content)
        content = re.sub(r'T_WIND\s+[\d.e+-]+', f'T_WIND               {T_bc:.6e}', content)
        
        ini_path.write_text(content)
    
    def _compile_pluto(self):
        """Compile PLUTO with current init.c"""
        result = subprocess.run(
            ["make", "clean"],
            cwd=self.work_dir,
            capture_output=True,
            text=True
        )
        
        result = subprocess.run(
            ["make"],
            cwd=self.work_dir,
            capture_output=True,
            text=True
        )
        
        if result.returncode != 0:
            raise RuntimeError(f"PLUTO compilation failed:\n{result.stderr}")
        
        if not (self.work_dir / "pluto").exists():
            raise RuntimeError("PLUTO executable not created")
    
    def _run_pluto(self, tstop):
        """
        Run PLUTO to specified stop time.
        
        Parameters
        ----------
        tstop : float
            Stop time in seconds
        """
        # Update pluto.ini with new tstop and output settings
        ini_path = self.work_dir / "pluto.ini"
        content = ini_path.read_text()
        import re
        content = re.sub(r'tstop\s+[\d.e+-]+', f'tstop            {tstop:.6e}', content)
        # Enable output at end of run (write one file per run)
        content = re.sub(r'dbl\s+[\d.e+-]+\s+-1', f'dbl              {tstop:.6e}  -1', content)
        ini_path.write_text(content)
        
        # Run PLUTO
        result = subprocess.run(
            ["./pluto"],
            cwd=self.work_dir,
            capture_output=True,
            text=True
        )
        
        if result.returncode != 0:
            # PLUTO sometimes returns non-zero even on success, check for output files
            if not list(self.work_dir.glob("data.*.dbl")):
                raise RuntimeError(f"PLUTO execution failed:\n{result.stderr}")
    
    def single_step_with_custom_bc(self, dt_target=None):
        """
        Advance simulation by one time step with custom boundary conditions.
        
        For PLUTO (batch mode), this compiles and runs to next output time.
        
        Parameters
        ----------
        dt_target : float, optional
            Target timestep (not used, PLUTO uses adaptive timestepping)
        
        Returns
        -------
        dt : float
            Actual timestep taken (s)
        """
        # Apply current BC
        self.apply_custom_bc()
        
        # Compile (only needed first time or if init.c changed)
        if self._current_step == 0:
            self._compile_pluto()
        
        # Determine stop time for this step
        # For now, use small steps (e.g., 0.1 day)
        dt_step = 8.64e3  # 0.1 day in seconds
        t_stop = self._current_time + dt_step
        
        # Run PLUTO
        self._run_pluto(t_stop)
        
        # Update state
        old_time = self._current_time
        self._current_time = t_stop
        self._current_step += 1
        
        return t_stop - old_time
    
    def get_state(self):
        """
        Get current simulation state.
        
        Returns
        -------
        dict with keys:
            't' : float - current simulation time (s)
            'r' : ndarray - radial positions (cm)
            'rho' : ndarray - mass density (g/cm³)
            'v' : ndarray - radial velocity (cm/s)
            'T' : ndarray - temperature (K)
            'P' : ndarray - pressure (dyne/cm²)
        """
        # Find latest output file
        output_files = sorted(self.work_dir.glob("data.*.dbl"))
        
        if not output_files:
            raise RuntimeError("No PLUTO output files found")
        
        # Read latest output with pyPLUTO
        try:
            # Add PLUTO Tools to path for pyPLUTO
            import sys
            pypluto_path = self.pluto_dir / "Tools" / "pyPLUTO"
            if str(pypluto_path) not in sys.path:
                sys.path.append(str(pypluto_path))
            
            import pyPLUTO.pload as pp
        except ImportError as e:
            raise ImportError(f"pyPLUTO not available: {e}. Check PLUTO installation.")
        
        # Extract file number
        latest_file = output_files[-1]
        file_num = int(latest_file.stem.split('.')[-1])
        
        # Load data (pyPLUTO expects path with trailing slash)
        work_dir_str = str(self.work_dir)
        if not work_dir_str.endswith('/'):
            work_dir_str += '/'
        D = pp.pload(file_num, w_dir=work_dir_str)
        
        # Extract 1D data
        r = D.x1  # radial positions (cm)
        rho = D.rho.squeeze()  # density (code units, should be cgs)
        v = D.vx1.squeeze()  # radial velocity (cm/s)
        P = D.prs.squeeze()  # pressure (dyne/cm²)
        
        # Calculate temperature: P = (rho/m_p) * k_B * T
        # T = P * m_p / (rho * k_B)
        T = P * PROTON_MASS / (rho * BOLTZMANN)
        
        return {
            't': self._current_time,
            'r': r,
            'rho': rho,
            'v': v,
            'T': T,
            'P': P
        }
    
    def finished(self):
        """Check if simulation has finished (never for PLUTO, controlled externally)"""
        return False
    
    def cleanup(self):
        """Clean up temporary files"""
        if self._temp_dir and self.work_dir.exists():
            shutil.rmtree(self.work_dir)
    
    def __del__(self):
        """Clean up on deletion"""
        try:
            if hasattr(self, '_temp_dir') and self._temp_dir:
                self.cleanup()
        except:
            pass


def _compute_parker_nozzle_solution(r, v_inner, n_inner, T_inner, gamma):
    """
    Compute analytical Parker nozzle solution for solar wind expansion.
    
    Treats spherical expansion as quasi-1D nozzle flow where A(r) = r².
    Assumes steady-state isentropic flow with perfect gas EOS.
    
    Parameters
    ----------
    r : array
        Radial positions (cm)
    v_inner : float
        Velocity at inner boundary (cm/s)
    n_inner : float
        Number density at inner boundary (cm⁻³)
    T_inner : float
        Temperature at inner boundary (K)
    gamma : float
        Adiabatic index
    
    Returns
    -------
    v, n, T, rho : arrays
        Velocity (cm/s), number density (cm⁻³), temperature (K), mass density (g/cm³)
    """
    from scipy.optimize import bisect
    
    rho_inner = n_inner * PROTON_MASS
    R_gas = BOLTZMANN
    
    # Compute Mach number and stagnation conditions at inner boundary
    c_inner = np.sqrt(gamma * R_gas * T_inner / PROTON_MASS)
    M_inner = v_inner / c_inner
    
    T_stag = T_inner * (1 + ((gamma - 1)/2)*(M_inner**2))
    p_stag = (n_inner * BOLTZMANN * T_inner) * ((1 + ((gamma - 1)/2)*(M_inner**2)) ** (gamma/(gamma - 1)))
    rho_stag = rho_inner * ((1 + ((gamma - 1)/2)*(M_inner**2)) ** (1/(gamma - 1)))
    
    # Area-Mach relation for nozzle flow
    def A_norm_calc(M, gamma):
        a = 2 / (gamma + 1)
        b = (gamma - 1) / 2
        c = (gamma + 1) / (2*(gamma - 1))
        return (1/M) * (a*(1 + b*M*M))**c
    
    A_inner = r[0]**2
    A_inner_norm = A_norm_calc(M_inner, gamma)
    A_star = A_inner / A_inner_norm
    
    # Solve for Mach number at each radius
    A = r**2
    A_norm = A / A_star
    
    def invert_A_for_M(M, gamma, A_n):
        return A_norm_calc(M, gamma) - A_n
    
    M = np.zeros(len(r))
    for i, a_n in enumerate(A_norm):
        M[i] = bisect(invert_A_for_M, 1 + 1e-12, 1e4, args=(gamma, a_n))
    
    # Compute static properties from isentropic relations
    T = T_stag / (1 + ((gamma - 1)/2)*(M**2))
    p = p_stag * (T/T_stag) ** (gamma/(gamma - 1))
    rho = rho_stag * (T/T_stag) ** (1/(gamma - 1))
    n = rho / PROTON_MASS
    c = np.sqrt(gamma * R_gas * T / PROTON_MASS)
    v = M * c
    
    return v, n, T, rho
